<?php

namespace Thanpa\PaycenterBundle\Tests\TicketIssue;

use Thanpa\PaycenterBundle\Service\TicketIssuer;
use Thanpa\PaycenterBundle\TicketIssue\TicketIssueRequest;

/**
 * Class TicketIssueRequestTest
 * @package Thanpa\PaycenterBundle\Tests\TicketIssue
 */
class TicketIssueRequestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * This test checks if a valid XML is generated by TicketIssuer class
     */
    public function testGetTicketMethod()
    {
        $guzzleMock = $this->getMockBuilder('\GuzzleHttp\Client')
            ->disableOriginalConstructor()
            ->getMock();

        $issuer = new TicketIssuer(
            $guzzleMock,
            'int',
            'int',
            'int',
            'string',
            'string',
            'https://paycenter.piraeusbank.gr/services/tickets/issuer.asmx'
        );

        $issuer
            ->setMerchantReference('string')
            ->setRequestType('string')
            ->setExpirePreAuth('unsignedByte')
            ->setAmount('decimal')
            ->setCurrencyCode('int')
            ->setInstallments('unsignedByte')
            ->setBnpl('unsignedByte')
            ->setParameters('string');

        $expected = file_get_contents(__DIR__.'/../Fixtures/ticketIssueRequest.xml');

        $this->assertEquals($expected, TicketIssueRequest::getBody($issuer));
    }
}
